# Generated by Django 4.2 on 2023-05-05 20:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("category", models.CharField()),
                ("realese_date", models.DateField()),
                ("synopsis", models.TextField()),
                ("author", models.CharField(max_length=50)),
                ("quantity", models.PositiveIntegerField()),
            ],
        ),
    ]
