# Generated by Django 4.2 on 2023-05-05 20:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("copys", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("borrowed_date", models.DateTimeField(null=True)),
                ("devolution_date", models.DateTimeField(null=True)),
                ("is_devoluted", models.BooleanField(default=False, null=True)),
                ("blocked_until", models.DateTimeField(null=True)),
                (
                    "copy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans_copys",
                        to="copys.copy",
                    ),
                ),
            ],
        ),
    ]
